"""add_session_title_minimal

Revision ID: 2362c399f28a
Revises: fa45315e8819
Create Date: 2025-12-04 23:27:14.078962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2362c399f28a'
down_revision: Union[str, Sequence[str], None] = 'fa45315e8819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('title', sa.String(length=200), nullable=True))
    op.add_column('sessions', sa.Column('id_title_suer_defined', sa.Boolean(), nullable=True))
    op.create_index('idx_session_title', 'sessions', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_session_title', table_name='sessions')
    op.drop_column('sessions', 'id_title_suer_defined')
    op.drop_column('sessions', 'title')
    # ### end Alembic commands ###
