"""Add workflow executions and conversation messages tables

Revision ID: 3d68e1934dd3
Revises: 3b0cbebfcff6
Create Date: 2025-11-08 15:26:29.527134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d68e1934dd3'
down_revision: Union[str, Sequence[str], None] = '3b0cbebfcff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_executions',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('request_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('routing_strategy', sa.String(length=50), nullable=True),
    sa.Column('completed_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('current_step', sa.String(length=50), nullable=True),
    sa.Column('progress', sa.String(length=10), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_time_seconds', sa.Integer(), nullable=True),
    sa.Column('total_tokens_used', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_history.analysis_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['fits_files.file_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workflow_id')
    )
    op.create_index('idx_workflow_created_at', 'workflow_executions', ['created_at'], unique=False)
    op.create_index('idx_workflow_session_id', 'workflow_executions', ['session_id'], unique=False)
    op.create_index('idx_workflow_status', 'workflow_executions', ['status'], unique=False)
    op.create_index('idx_workflow_user_id', 'workflow_executions', ['user_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_executions.workflow_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('idx_message_created_at', 'conversation_messages', ['created_at'], unique=False)
    op.create_index('idx_message_session_id', 'conversation_messages', ['session_id'], unique=False)
    op.create_index('idx_message_session_sequence', 'conversation_messages', ['session_id', 'sequence_number'], unique=False)
    op.create_index('idx_message_workflow_id', 'conversation_messages', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_message_workflow_id', table_name='conversation_messages')
    op.drop_index('idx_message_session_sequence', table_name='conversation_messages')
    op.drop_index('idx_message_session_id', table_name='conversation_messages')
    op.drop_index('idx_message_created_at', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index('idx_workflow_user_id', table_name='workflow_executions')
    op.drop_index('idx_workflow_status', table_name='workflow_executions')
    op.drop_index('idx_workflow_session_id', table_name='workflow_executions')
    op.drop_index('idx_workflow_created_at', table_name='workflow_executions')
    op.drop_table('workflow_executions')
    # ### end Alembic commands ###
