"""edit is_title_user_defined column's name

Revision ID: 70dff979aea4
Revises: dd51063bce49
Create Date: 2025-12-05 14:22:21.723006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70dff979aea4'
down_revision: Union[str, Sequence[str], None] = 'dd51063bce49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('is_title_user_defined', sa.Boolean(), nullable=True))
    op.drop_column('sessions', 'id_title_suer_defined')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('id_title_suer_defined', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('sessions', 'is_title_user_defined')
    # ### end Alembic commands ###
